

all: Colleen Grace Sully

clean:
	rm -f Colleen Grace Sully Grace_kid.c Sully_* a.out
	echo " { \033[34mD E L E T E D\033[0m }"

re: clean all

Colleen:
	gcc Colleen.c -o Colleen
	echo "~< \033[032mC O L L E E N\033[00m >~"

Grace:
	gcc Grace.c -o Grace
	echo "  ~< \033[033mG R A C E\033[00m >~"

Sully:
	gcc Sully.c -o Sully
	echo "  ~< \033[034mS U L L Y\033[00m >~"

.SILENT: